"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Check, ChevronsUpDown, Search, FileText } from "lucide-react";

import {
  Home,
  User,
  Settings,
  Mail,
  Calendar,
  FileTextIcon,
  Book,
  BookOpen,
  Bookmark,
  Info,
  HelpCircle,
  Phone,
  MapPin,
  ShoppingCart,
  CreditCard,
  Heart,
  Star,
  Bell,
  Clock,
  Image,
  Video,
  Music,
  Folder,
  File,
  Upload,
  Download,
  Link,
  Share,
  Send,
  MessageSquare,
  Users,
  UserPlus,
  UserMinus,
  UserCheck,
  Lock,
  Unlock,
  Shield,
  Key,
  AlertCircle,
  AlertTriangle,
  CheckCircle,
  XCircle,
  Eye,
  EyeOff,
  Menu,
  MoreHorizontal,
  MoreVertical,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Plus,
  Minus,
  X,
  CheckIcon,
  Edit,
  Trash,
  Trash2,
  Copy,
  Clipboard,
  Save,
  Printer,
  ExternalLink,
  RefreshCw,
  RotateCw,
  Filter,
  SearchIcon,
  Zap,
  Activity,
  BarChart,
  PieChart,
  LineChart,
  TrendingUp,
  TrendingDown,
  Layers,
  Grid,
  List,
  Table,
  Tag,
  Flag,
  Globe,
  Map,
  Compass,
  Smartphone,
  Tablet,
  Laptop,
  Monitor,
  Wifi,
  Bluetooth,
  Battery,
  BatteryCharging,
  Sun,
  Moon,
  Cloud,
  CloudRain,
  CloudSnow,
  CloudLightning,
  Wind,
  Thermometer,
  Umbrella,
  Camera,
  Mic,
  Speaker,
  Headphones,
  Play,
  Pause,
  CircleStopIcon as Stop,
  SkipBack,
  SkipForward,
  Volume,
  VolumeX,
  Maximize,
  Minimize,
  Type,
  Underline,
  Italic,
  Bold,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  Code,
  Terminal,
  GitBranch,
  AppleIcon as Safari,
  DotIcon as Edge,
  Coffee,
  Gift,
  ShoppingBag,
  Package,
  Truck,
  DollarSign,
  Percent,
  Award,
  Briefcase,
  Wrench,
  Scissors,
  Paperclip,
  Smile,
  Frown,
  Meh,
  ThumbsUp,
  ThumbsDown,
  Feather,
  Hash,
  AtSign,
  Anchor,
  Infinity,
  Hexagon,
  Triangle,
  Square,
  Circle,
  Box,
  CuboidIcon as Cube,
  Aperture,
  Droplet,
  Cpu,
  Database,
  Server,
  Power,
  Command,
  Shuffle,
  Repeat,
  Loader,
  AlertOctagon,
  Archive,
  Columns,
  Crosshair,
  Delete,
  Disc,
  DivideCircle,
  DivideSquare,
  Edit2,
  Edit3,
  FileMinus,
  FilePlus,
  Film,
  FolderMinus,
  FolderPlus,
  GitCommit,
  GitMerge,
  GitPullRequest,
  HardDrive,
  Inbox,
  Layout,
  LifeBuoy,
  Link2,
  LogIn,
  LogOut,
  Maximize2,
  Minimize2,
  MousePointer,
  Move,
  Navigation,
  Navigation2,
  Octagon,
  PlusCircle,
  PlusSquare,
  Pocket,
  Radio,
  RefreshCcw,
  Rewind,
  RotateCcw,
  Rss,
  SearchIcon as SearchIconDuplicate,
  Share2,
  ShieldOff,
  Sidebar,
  Slash,
  Sliders,
  Sunrise,
  Sunset,
  Target,
  ToggleLeft,
  ToggleRight,
  Tv,
  Voicemail,
  Volume1,
  Volume2,
  XOctagon,
  XSquare,
  ZapOff,
  ZoomIn,
  ZoomOut,
} from "lucide-react";

const iconMap = {
  Home,
  User,
  Settings,
  Mail,
  Calendar,
  FileText: FileTextIcon,
  Book,
  BookOpen,
  Bookmark,
  Info,
  HelpCircle,
  Phone,
  MapPin,
  ShoppingCart,
  CreditCard,
  Heart,
  Star,
  Bell,
  Clock,
  Image,
  Video,
  Music,
  Folder,
  File,
  Upload,
  Download,
  Link,
  Share,
  Send,
  MessageSquare,
  Users,
  UserPlus,
  UserMinus,
  UserCheck,
  Lock,
  Unlock,
  Shield,
  Key,
  AlertCircle,
  AlertTriangle,
  CheckCircle,
  XCircle,
  Eye,
  EyeOff,
  Menu,
  MoreHorizontal,
  MoreVertical,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Plus,
  Minus,
  X,
  Check: CheckIcon,
  Edit,
  Trash,
  Trash2,
  Copy,
  Clipboard,
  Save,
  Printer,
  ExternalLink,
  RefreshCw,
  RotateCw,
  Filter,
  Search: SearchIcon,
  Zap,
  Activity,
  BarChart,
  PieChart,
  LineChart,
  TrendingUp,
  TrendingDown,
  Layers,
  Grid,
  List,
  Table,
  Tag,
  Flag,
  Globe,
  Map,
  Compass,
  Smartphone,
  Tablet,
  Laptop,
  Monitor,
  Wifi,
  Bluetooth,
  Battery,
  BatteryCharging,
  Sun,
  Moon,
  Cloud,
  CloudRain,
  CloudSnow,
  CloudLightning,
  Wind,
  Thermometer,
  Umbrella,
  Camera,
  Mic,
  Speaker,
  Headphones,
  Play,
  Pause,
  Stop,
  SkipBack,
  SkipForward,
  Volume,
  VolumeX,
  Maximize,
  Minimize,
  Type,
  Underline,
  Italic,
  Bold,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  Code,
  Terminal,
  GitBranch,
  Safari,
  Edge,
  Coffee,
  Gift,
  ShoppingBag,
  Package,
  Truck,
  DollarSign,
  Percent,
  Award,
  Briefcase,
  Wrench,
  Scissors,
  Paperclip,
  Smile,
  Frown,
  Meh,
  ThumbsUp,
  ThumbsDown,
  Feather,
  Hash,
  AtSign,
  Anchor,
  Infinity,
  Hexagon,
  Triangle,
  Square,
  Circle,
  Box,
  Cube,
  Aperture,
  Droplet,
  Cpu,
  Database,
  Server,
  Power,
  Command,
  Shuffle,
  Repeat,
  Loader,
  AlertOctagon,
  Archive,
  Columns,
  Crosshair,
  Delete,
  Disc,
  DivideCircle,
  DivideSquare,
  Edit2,
  Edit3,
  FileMinus,
  FilePlus,
  Film,
  FolderMinus,
  FolderPlus,
  GitCommit,
  GitMerge,
  GitPullRequest,
  HardDrive,
  Inbox,
  Layout,
  LifeBuoy,
  Link2,
  LogIn,
  LogOut,
  Maximize2,
  Minimize2,
  MousePointer,
  Move,
  Navigation,
  Navigation2,
  Octagon,
  PlusCircle,
  PlusSquare,
  Pocket,
  Radio,
  RefreshCcw,
  Rewind,
  RotateCcw,
  Rss,
  Share2,
  ShieldOff,
  Sidebar,
  Slash,
  Sliders,
  Sunrise,
  Sunset,
  Target,
  ToggleLeft,
  ToggleRight,
  Tv,
  Voicemail,
  Volume1,
  Volume2,
  XOctagon,
  XSquare,
  ZapOff,
  ZoomIn,
  ZoomOut,
};

const iconNames = Object.keys(iconMap);

interface IconPickerProps {
  value: string;
  onChange: (value: string) => void;
}

export default function IconPicker({ value, onChange }: IconPickerProps) {
  const [searchTerm, setSearchTerm] = useState("");
  const [isOpen, setIsOpen] = useState(false);

  const filteredIcons = iconNames.filter((name) =>
    name.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const renderIcon = (iconName: string) => {
    const IconComponent = iconMap[iconName as keyof typeof iconMap];
    return IconComponent ? (
      <IconComponent className="h-4 w-4" />
    ) : (
      <FileText className="h-4 w-4" />
    );
  };

  const CurrentIcon =
    value && iconMap[value as keyof typeof iconMap] ? (
      renderIcon(value)
    ) : (
      <FileText className="h-4 w-4" />
    );

  return (
    <Popover open={isOpen} onOpenChange={setIsOpen}>
      <PopoverTrigger asChild>
        <Button
          variant="outline"
          role="combobox"
          aria-expanded={isOpen}
          className="justify-between"
        >
          <div className="flex items-center gap-2">
            {CurrentIcon}
            <span>{value || "Pasirinkite ikoną"}</span>
          </div>
          <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
        </Button>
      </PopoverTrigger>
      <PopoverContent className="w-64 p-0">
        <div className="flex items-center border-b px-3 py-2">
          <Search className="mr-2 h-4 w-4 shrink-0 opacity-50" />
          <Input
            placeholder="Ieškoti ikonų..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="border-0 p-0 focus-visible:ring-0"
          />
        </div>
        <ScrollArea className="h-72">
          <div className="grid grid-cols-3 gap-1 p-2">
            {filteredIcons.map((iconName) => (
              <Button
                key={iconName}
                variant="ghost"
                size="sm"
                className={`flex items-center justify-start gap-2 ${
                  value === iconName ? "bg-accent" : ""
                }`}
                onClick={() => {
                  onChange(iconName);
                  setIsOpen(false);
                }}
              >
                {renderIcon(iconName)}
                {value === iconName && <Check className="h-4 w-4 ml-auto" />}
              </Button>
            ))}
          </div>
        </ScrollArea>
      </PopoverContent>
    </Popover>
  );
}
